name: ASTR 480 Autograder

on:
  - push
  - workflow_dispatch

permissions:
  actions: read
  contents: read

jobs:
  autograding:
    name: Autograding

    runs-on: ubuntu-24.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.12

      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true

      - name: Install dependencies
        run: |
          uv sync --no-dev --frozen

      - name: Test with pytest
        id: pytest-test
        uses: classroom-resources/autograding-command-grader@v1
        with:
          test-name: Pytest test
          command: pytest
          timeout: 60
          max-score: 100

      - name: Autograding Reporter
        uses: ./
        env:
          PYTEST-TEST_RESULTS: "${{steps.pytest-test.outputs.result}}"
        with:
          runners: pytest-test
